production:
  adapter: mysql
  username: root
  database: openmrs_thyolo #st_gabriels_bart2 #openmrs_nkhotakota
  password: root.letusout!
  host: localhost
  pool: 500

development:
  adapter: mysql
  username: root
  database: openmrs_queens2 #thyolo_new_data #openmrs_st_gabriels_bart2 #openmrs_nkhotakota
  password: root
  host: 192.168.43.175

test: &TEST
  adapter: mysql
  database: root
  username: bart2_db
  password: your_password
  host: localhost

cucumber:
  <<: *TEST
test: &TEST

healthdata:
  adapter: mysql
  database: healthdata
  username: root
  password: root.letusout!
  host: localhost
  pool: 500
